feat: 杜绝浪费，在Job上增加相关特性，避免不必要的开销 #970
Tencent/bk-ci pull request #2454
Opened 2020-08-31 12:21 UTC by huangjiao-heart

2020-08-31 12:29 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-ci?pullRequest=2454) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-ci?pullRequest=2454) before we can accept your contribution.<br/><hr/>**johuang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-ci?pullRequest=2454) it.</sub>

2020-08-31 16:03 UTC, irwinsun commented on src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/PipelineDispatchService.kt
> +                val vmType = JobQuotaVmType.parse(pipelineAgentStartupEvent.dispatchType)
这里要处理一下，如果dispatchType因为异常的值，导致parse异常抛出了。后续流程会都断掉了

2020-08-31 16:04 UTC, irwinsun commented on src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/dao/JobQuotaSystemDao.kt
> +            vmType = JobQuotaVmType.parse(record.vmType),
JobQuotaVmType.parse 可能会抛出异常，导致调用流程中断

2020-08-31 16:09 UTC, irwinsun commented on src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/api/ServiceJobQuotaBusinessResource.kt
> +    fun addRunningJob(
同为POST方法的
@Path("/{projectId}/{vmType}/{buildId}/{vmSeqId}")路径
与
addRunningAgent 的 @Path("/agent/{projectId}/{buildId}/{vmSeqId}")

可能存在冲突 比如请求的projectId为agent时，会出现二义性，有可能会调用出错

2020-09-01 03:34 UTC, huangjiao-heart commented on src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/api/ServiceJobQuotaBusinessResource.kt
> +    fun addRunningJob(
已修改

2020-09-01 03:34 UTC, huangjiao-heart commented on src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/PipelineDispatchService.kt
> +                val vmType = JobQuotaVmType.parse(pipelineAgentStartupEvent.dispatchType)
已修改

2020-09-01 03:38 UTC, irwinsun approved these changes

2020-09-08 04:16 UTC, irwinsun commented on src/backend/ci/core/common/common-auth/common-auth-blueking/src/main/kotlin/com/tencent/devops/common/auth/code/BkAuthServiceCode.kt
> +// const val GLOBAL_SCOPE_TYPE = "system"
参数在别的地方有引用，不能注释掉

2020-09-08 04:16 UTC, irwinsun commented on src/backend/ci/core/common/common-auth/common-auth-blueking/src/main/kotlin/com/tencent/devops/common/auth/code/BkAuthServiceCode.kt
> +// const val BK_DEVOPS_SCOPE = "bk_ci"
参数在下面有引用，不能注释掉

2020-09-08 04:18 UTC, irwinsun commented on src/backend/ci/core/project/api-project/build.gradle
> +    compile project(":core:common:common-auth:common-auth-blueking")
这里需要改为依赖 common-auth-api
blueking为具体业务实现，不应该作为api层的依赖

2020-09-08 04:19 UTC, irwinsun requested changes
需要针对上述进行必要修改

2020-09-08 04:28 UTC, irwinsun commented
#970

2020-09-08 06:20 UTC, huangjiao-heart commented on src/backend/ci/core/project/api-project/build.gradle
> +    compile project(":core:common:common-auth:common-auth-blueking")
已调整

2020-09-08 06:56 UTC, irwinsun commented on src/backend/ci/core/common/common-auth/common-auth-blueking/src/main/kotlin/com/tencent/devops/common/auth/code/BkAuthServiceCode.kt
> +// const val BK_DEVOPS_SCOPE = "bk_ci"
已经在AuthConstants上定义，此处重复，可移除

2020-09-08 06:56 UTC, irwinsun commented on src/backend/ci/core/common/common-auth/common-auth-blueking/src/main/kotlin/com/tencent/devops/common/auth/code/BkAuthServiceCode.kt
> +// const val GLOBAL_SCOPE_TYPE = "system"
已经在AuthConstants上定义，此处重复，可移除

2020-09-08 06:57 UTC, irwinsun approved these changes

2020-09-08 06:58 UTC, merged