pref: 签名服务External类接口不做文件md5校验 #3568
Tencent/bk-ci pull request #3583
Opened 2021-01-22 13:08 UTC by royalhuang

增加不做md5校验已经保证所有任务执行完毕再退出服务 #3568

2021-01-25 04:00 UTC, irwinsun approved these changes

2021-01-25 04:04 UTC, irwinsun requested changes

2021-01-25 04:04 UTC, irwinsun commented on src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/AsyncSignService.kt
> +    private val signExecutorService = Executors.newFixedThreadPool(10)
这里队列是无限的，需要考虑爆队列的场景。
要做有损的设计

2021-02-19 09:18 UTC, royalhuang commented on src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/AsyncSignService.kt
> +    private val signExecutorService = Executors.newFixedThreadPool(10)
已在[新的提交](https://github.com/Tencent/bk-ci/pull/3583/commits/0d045a2e934f3840fd8cf6abb965739d4113093d)中解决

2021-02-24 08:23 UTC, irwinsun approved these changes

2021-02-24 08:23 UTC, merged