bug: 修复混布时出现cpu和内存可用量上报为负值
Tencent/bk-ci pull request #5900
Opened 2021-12-28 08:27 UTC by flyy1012

2021-12-28 11:43 UTC, Lwxiang approved these changes
LGTM

2021-12-28 11:43 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/k8s/operator.go
> +		}
这里可以考虑用Warn级别的日志，这里只是跳过，个别节点统计出问题不影响整体。

日志内容可以考虑把`allocatedResource.Cpu().Value()`打出来，并说明将会"跳过"这个节点的上报。

另外，除了在k8s-operator层做限制，是否考虑在crm层也统一做一下限制？因为operator是上报的节点信息，资源组的概念还是在crm层维护的，可以考虑不管哪个operator上报的数据，一旦不合法就丢弃该节点，保护该资源组的资源可用性。

2021-12-28 11:43 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/k8s/operator.go
> +
不适用的函数，就直接删掉好了，如果需要回滚就交给版本管理来做，尽量不要使用大块的代码注释。

2021-12-28 11:43 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/k8s/operator.go
>  func getPodsTotalRequestsAndLimits(nodeName string, podList *coreV1.PodList) coreV1.ResourceList {
可以考虑把函数名改为`getPodsTotalRequests`，现在不涉及limit了

2021-12-29 03:33 UTC, Lwxiang requested changes

2021-12-29 03:33 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/bcs.go
>  		newBlock.CPUUsed += NodeInfo.CPUUsed
我看你去掉了operator层的判断，把逻辑放在了crm层的`availableIst`，这样有个问题在于，错误的instance不会被统计进去，但是错误的cpuTotal和memTotal都统计进去了。

可以在一开始就这样做：
```golang
for _, NodeInfo := range nodeInfoList {
    go recordResource(NodeInfo)

    if NodeInfo.Disabled {
        continue
    }

    // 由NodeInfo的成员函数Valid()来判断该节点是否合法
    // 至于节点合法需要满足什么条件, 统统放到Valid()里面去处理，可以避免统计流程里出现太多校验规则
    if !NodeInfo.Valid() {
        blog.Warnf("crm: get node ....")
        continue
    }
```

至于`NodeInfo.Valid()`，可以是一个这样的函数：
```golang
func (ni *NodeInfo) Valid() bool {
    return ni.CPUTotal < 0 || ni.MemTotal < 0 || ni.DiskTotal < 0
}
```

这样就可以保证，在一开始就排除非法节点，避免cpu、mem、instance等各类资源数据被污染。

2021-12-29 03:33 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/bcs.go
>  		newBlock.CPUUsed += NodeInfo.CPUUsed
另外需要注意一下日志的级别，`blog.V(5)`是个很低的级别，一般生产环境不会开到`-v 5`的日志级别。不过考虑到资源同步的频率很快，warning级别日志可能会刷频刷很多，但V(5)基本就告不出来了，这个可以综合权衡一下。

2021-12-29 06:58 UTC, Lwxiang approved these changes
LGTM

2021-12-29 07:11 UTC, tming reviewed
ok

2021-12-29 07:13 UTC, tming approved these changes
ok

2021-12-29 07:13 UTC, merged