feat: support diffrent instance typ
Tencent/bk-ci pull request #5967
Opened 2022-01-06 08:24 UTC by flyy1012

2022-01-06 11:40 UTC, Lwxiang requested changes

2022-01-06 11:40 UTC, Lwxiang commented on src/backend/booster/helm/charts/bktbs/templates/server/serviceMonitor.yaml
> -{{- if .Values.bkMonitorConfig.enable -}}
这部分是社区版的修改要求么？虽然改动少，但还是建议分两个pr出来，每个pr里做一个事情。

2022-01-06 11:40 UTC, Lwxiang commented on src/backend/booster/server/pkg/api/v2/api.go
> -		Verb: "GET", Path: "/health", Params: nil, Handler: api.MasterRequired(Health),
同样的，这里的改动是为了解决helm update过程中出现的health接口转发问题，应该专门开一个issue和pr处理。

2022-01-06 11:40 UTC, Lwxiang commented on src/backend/booster/server/config/config.go
> +type QueuePerInstance struct {
这里的命名有点奇怪，`QueuePerInstance`字面意思是每个实例的队列？

从实际意义上来说，这个结构体应该是描述crm下支持的一种实例类型，可以考虑`InstanceType`之类更直接的命名。

2022-01-06 11:40 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/manager.go
> +	GetQueueInstance(queuePerInstance config.QueuePerInstance) *config.QueuePerInstance
这里有几个问题：

1. `GetInstanceType`比`GetQueueInstance`更合适一些，queue这个概念，属于上层流程的概念，不应该侵入到资源管理层，queue只是上层抽象出来用来消费资源的一个模型。
2. 这里的入参不应该复用这个对象, 可以直接用 (platform, group string), 需要的只是这个主键而已。
3. City这样的命名，是由于历史原因遗留下来的，现在k8s集群的标签已经不是city了，我们在启动参数中有一个`crm_bcs_group_label_key`，因此可以用group或来指代这个参数，也更符合它的实际意义。

2022-01-06 11:40 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/bcs.go
> +		platform = "default-platform"
对default和unknown的定义有多个来源了，下面的`getBlockKey`也会做类似的判断，这个需要把来源统一。

如果`getBlockKey`不满足，就应该改造它，不建议直接复制一份出来，后期这个定义来源会比较难管理。

2022-01-06 11:40 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/bcs.go
> +	platform := attributes[AttributeKeyPlatform]
这个去掉的话，如果上报上来的attributes没有platform这个key，crm的主协程可能会panic，需要保留。

2022-01-06 11:40 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/mesos/operator.go
> +	//data = strings.Replace(data, templateVarMem, fmt.Sprintf("%.2f", o.conf.BcsMemPerInstance), -1)
不用的代码直接删掉了，后面其他人维护不小心取消注释的话会是很严重的问题。

2022-01-06 11:40 UTC, Lwxiang commented on src/backend/booster/server/pkg/resource/crm/operator/k8s/operator.go
> +		}
这里可以break

所有的条件应该可以直接 > 0，负值在这里是没有用的

2022-01-24 07:08 UTC, flyy1012 commented on src/backend/booster/helm/charts/bktbs/templates/server/serviceMonitor.yaml
> -{{- if .Values.bkMonitorConfig.enable -}}
done

2022-01-26 09:14 UTC, closed without merging