Feat 5914
Tencent/bk-ci pull request #6280
Opened 2022-03-08 03:34 UTC by liuandhisgithub

#5914

2022-03-09 01:50 UTC, mingshewhe commented on support-files/sql/1001_ci_process_ddl_mysql.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=1018 DEFAULT CHARSET=utf8mb4;
AUTO_INCREMENT 从0开始

2022-03-16 01:11 UTC, irwinsun requested changes

2022-03-16 01:11 UTC, irwinsun commented on src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/config/PollSvnConfig.kt
> +    private var interval: Long = 60
如果用户设置为1呢？ 建议有个最小和最大的范围限制检查

2022-03-16 01:11 UTC, irwinsun commented on src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/config/PollSvnConfig.kt
> +    private var interval: Long = 60
比如设置过小，以每秒触发可能会对svn服务器以及流水线平台产生不健康的影响

2022-03-16 01:11 UTC, irwinsun commented on src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/service/TriggerSvnService.kt
> +                logger.info("")
这句代码的意义是什么？

2022-03-18 07:24 UTC, closed without merging