feat: 支持本地空闲资源参与分布式任务的执行
Tencent/bk-ci pull request #6283
Opened 2022-03-08 09:10 UTC by tming

1. 支持本地空闲资源参与分布式任务的执行
2. bk-ubt-tool的任务策略支持参数开关
3. remote的slot部分调整，在disable work后相应的调整slot数量

2022-03-08 11:59 UTC, flyy1012 commented on src/backend/booster/bk_dist/controller/pkg/manager/resource/mgr.go
> +		blog.Infof("resource: tomtian got jobs %d for host %s", jobs, v)
这里应该是测试的日志，是否可以去掉

2022-03-08 12:07 UTC, flyy1012 commented on src/backend/booster/bk_dist/ubttool/command/command.go
> +	FlagMostDependFirst = "most_depend_first"
这个应该是另外一个需求的commit，是否分成两次提交更好点

2022-03-08 12:13 UTC, flyy1012 commented on src/backend/booster/bk_dist/controller/pkg/manager/remote/slots.go
> +	// }
不知道这段是否应该注释，如果注释了usageLimit这个变量并没有被使用

2022-03-08 12:47 UTC, Lwxiang requested changes

2022-03-08 12:47 UTC, Lwxiang commented on src/backend/booster/bk_dist/controller/pkg/manager/manager.go
> +	}
这里的处理可以内聚一些，这里的defer的对等操作是隐含在checkRunWithLocalResource里的，理解起来比较复杂，不易于后续维护。

可以考虑把这些操作细节都放到具体的method里面，让调用者只关心宏观的操作。例如，用户只关心check和clear。
m.checkIfRunWithLocalResource(work)
defer m.clearIfRunWithLocalResource(work)

2022-03-08 12:47 UTC, Lwxiang commented on src/backend/booster/bk_dist/controller/pkg/manager/remote/slots.go
> +			v.limit = wr.totalSlots
usage的limit可能被用户手动指定过，这里如果全部指定为totalSlots的最新值，会不会覆盖导致用户的配置失效？

2022-03-09 01:46 UTC, tming commented on src/backend/booster/bk_dist/controller/pkg/manager/manager.go
> +	}
可以，我加个函数

2022-03-09 01:48 UTC, tming commented on src/backend/booster/bk_dist/controller/pkg/manager/remote/slots.go
> +	// }
准备注释掉的，这个地方直接赋值，主要考虑性能问题，在remote的slot里面，实际只会用到 JobUsageRemoteExe，并且这个现在默认都是为0，没有用户赋值的需求，短期内看不到用户设置的需求，所以直接特例化了

2022-03-09 01:50 UTC, tming commented on src/backend/booster/bk_dist/controller/pkg/manager/remote/slots.go
> +			v.limit = wr.totalSlots
这儿只会用到 JobUsageRemoteExe，并且现在只会为0，短期内看不到有用户设置的需求，所以直接特例化，维护时更清晰，性能更好

2022-03-09 01:51 UTC, tming commented on src/backend/booster/bk_dist/controller/pkg/manager/resource/mgr.go
> +		blog.Infof("resource: tomtian got jobs %d for host %s", jobs, v)
的确是测试日志，我检查时漏掉了

2022-03-09 01:52 UTC, tming commented on src/backend/booster/bk_dist/ubttool/command/command.go
> +	FlagMostDependFirst = "most_depend_first"
这个改动不大，提交时已经修改验证过了，回退比较麻烦，大家包容下 ：）

2022-03-10 06:34 UTC, flyy1012 approved these changes

2022-03-14 04:19 UTC, closed without merging