蓝盾task执行超时场景下，BK_CI_BUILD_FAIL_TASKS变量为空 #5249
Tencent/bk-ci pull request #6318
Opened 2022-03-15 03:03 UTC by yjieliang

蓝盾task执行超时场景下，BK_CI_BUILD_FAIL_TASKS变量为空 #5249

2022-03-18 01:55 UTC, carlyin0801 approved these changes
ok

2022-03-21 01:12 UTC, irwinsun requested changes

2022-03-21 01:12 UTC, irwinsun commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
> +                    pipelineTaskService.createFailTaskVar(
此处多出来的代码与else重复，需要精简，可将 result.errorCode == ErrorCode.USER_TASK_OUTTIME_LIMIT 放到下面else里判断。
<img width="794" alt="image" src="https://user-images.githubusercontent.com/16686129/159194401-48df8138-e23f-49ab-9093-4bc9f620938a.png">

2022-03-21 01:46 UTC, irwinsun approved these changes

2022-03-21 01:59 UTC, merged