feat: 流水线支持设置并发组执行策略 #6521
Tencent/bk-ci pull request #6540
Opened 2022-04-15 02:09 UTC by yongyiduan

2022-04-15 07:49 UTC, royalhuang approved these changes

2022-04-17 08:27 UTC, irwinsun commented on support-files/sql/2008_ci_process-update_v1.8_mysql.sql
> +	IF NOT EXISTS(SELECT 1
1001_ci_process_ddl_mysql.sql需要补充

2022-04-17 09:00 UTC, irwinsun commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
> +                        pipelineRuntimeExtService.popAllConcurrencyGroupBuildInfo(this)
此处逻辑与下面的cancelBuildPipeline 似有重复

2022-04-17 09:00 UTC, irwinsun commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeExtService.kt
> +    fun popAllConcurrencyGroupBuildInfo(
与 QueueIntercepter.cancelBuildPipeline 相比，是否有必要做这一步？

2022-04-17 09:03 UTC, irwinsun reviewed
2点：
1、SQL DDL 补充
2、 QueueIntercepter.cancelBuildPipeline与PipelineRuntimeExtService.popAllConcurrencyGroupBuildInfo 是否存在不必要的操作

2022-04-17 09:10 UTC, irwinsun requested changes
注意BuildInfo 存在Json对象
从目前来看 pipelineRuntimeService.getBuildInfoListByConcurrencyGroup 返回了过多的内容
建议重新修改函数名称，并DAO层只查取返回需要的字段，
目前用途仅用于读取pipelineId, buildId, 以及 count计数，不需要将整个记录字段都返回

2022-04-17 14:20 UTC, yongyiduan commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
> +                        pipelineRuntimeExtService.popAllConcurrencyGroupBuildInfo(this)
已去掉popAllConcurrencyGroupBuildInfo

2022-04-18 02:58 UTC, irwinsun approved these changes

2022-04-18 02:58 UTC, merged