bug: 构建历史中没有流水线完成后上传的构件 #6538
Tencent/bk-ci pull request #6544
Opened 2022-04-15 04:24 UTC by yaoxuwan

bug: 构建历史中没有流水线完成后上传的构件 #6538

2022-04-28 03:14 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-ci?pullRequest=6544) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-ci?pullRequest=6544) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-ci?pullRequest=6544) it.</sub>

2022-05-09 03:07 UTC, irwinsun requested changes
skipEmptyObjectMapper 需要保持一致,差异部分通过参数传入

并需要补充现有JsonUtil单测,针对变更部分的测试

2022-05-09 03:07 UTC, irwinsun commented on src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/JsonUtil.kt
> +            val javaTimeModule = JavaTimeModule()
skipEmptyObjectMapper 需要保持一致,差异部分通过参数传入

2022-05-09 14:05 UTC, irwinsun approved these changes

2022-05-09 14:05 UTC, merged