插件突出执行失败的错误类型，引导用户咨询对应责任人 #6068
Tencent/bk-ci pull request #6593
Opened 2022-04-21 07:13 UTC by yongyiduan

插件突出执行失败的错误类型，引导用户咨询对应责任人 #6068

2022-05-06 06:39 UTC, royalhuang approved these changes

2022-05-06 07:31 UTC, irwinsun commented on src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/utils/CommonUtils.kt
> +                val commonConfig = SpringContextUtil.getBean(CommonConfig::class.java)
会导致EN的全变成依赖配置项,  需要研究下LocaleContextHolder.getLocale()的实现

2022-05-06 07:31 UTC, irwinsun requested changes
需要重新对LocaleContextHolder.getLocale()进行评估

2022-05-09 07:32 UTC, irwinsun approved these changes

2022-05-09 07:32 UTC, merged