feat: 对接bcs构建资源 #6658
Tencent/bk-ci pull request #6877
Opened 2022-05-31 02:16 UTC by sawyersong2

2022-06-07 04:10 UTC, irwinsun commented on src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/CredentialUtils.kt
> +    fun getCredential(
新增没有具体用途

2022-06-07 04:17 UTC, irwinsun commented on src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/BuildType.kt
> +    THIRD_PARTY_BCS("蓝鲸容器平台", listOf(OS.LINUX), false, false, false),
PUBLIC_BCS g两者的区别？

另外不是复用 现在 DOCKER 么

2022-06-07 04:18 UTC, irwinsun commented on src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/agent/ThirdPartyBcsDispatchType.kt
> +    displayName
Add names to call arguments

2022-06-07 04:18 UTC, irwinsun commented on src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/bcs/PublicBcsDispatchType.kt
> +) : StoreDispatchType(if (image.isNullOrBlank())
Add names to call arguments

2022-06-07 04:19 UTC, irwinsun commented on scripts/bkenv.properties
> +BK_CI_BCS_HOST=
无默认值需要考虑部署

2022-06-07 04:24 UTC, irwinsun commented on src/backend/ci/core/dispatch-bcs/biz-dispatch-bcs/src/main/kotlin/com/tencent/devops/dispatch/bcs/client/BcsClientCommon.kt
> +    @Value("\${devopsGateway.idcProxy:#{null}}")
不单独定义使用，直接引用CommonConfig.devopsIdcProxyGateway

2022-06-07 04:24 UTC, irwinsun commented on src/backend/ci/core/dispatch-bcs/biz-dispatch-bcs/src/main/kotlin/com/tencent/devops/dispatch/bcs/client/BcsClientCommon.kt
> +    fun url(realUrl: String) = "$idcProxy/proxy-devnet?url=${URLEncoder.encode(realUrl, "UTF-8")}"
不单独定义使用，直接引用CommonConfig.devopsIdcProxyGateway

2022-06-07 04:28 UTC, irwinsun commented on src/backend/ci/core/dispatch-bcs/biz-dispatch-bcs/src/main/kotlin/com/tencent/devops/dispatch/bcs/client/BcsBuilderClient.kt
> +    val bcsApiUrl: String = ""
建议将3个BcsClient的此api配置收到BcsClientCommon

2022-06-07 04:29 UTC, irwinsun commented on src/backend/ci/core/dispatch-bcs/biz-dispatch-bcs/src/main/kotlin/com/tencent/devops/dispatch/bcs/client/BcsJobClient.kt
> +    val bcsApiUrl: String = ""
建议将3个BcsClient的此api配置收到BcsClientCommon，不暴露给Client

2022-06-07 04:29 UTC, irwinsun commented on src/backend/ci/core/dispatch-bcs/biz-dispatch-bcs/src/main/kotlin/com/tencent/devops/dispatch/bcs/client/BcsTaskClient.kt
> +    val bcsApiUrl: String = ""
建议将3个BcsClient的此api配置收到BcsClientCommon，不暴露给Client

2022-06-07 06:17 UTC, irwinsun commented on src/backend/ci/core/dispatch-bcs/biz-dispatch-bcs/src/main/kotlin/com/tencent/devops/dispatch/bcs/utils/BcsJobRedisUtils.kt
> +    // TODO: 这里要问下左涛看会不会和devcloud冲突
todo

2022-06-07 06:23 UTC, irwinsun commented on src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/enums/JobQuotaVmType.kt
> +    DOCKER_BCS("Docker on Bcs"),
确认下是否多余

2022-06-07 06:23 UTC, irwinsun commented on scripts/bkenv.properties
> +BK_CI_BCS_HOST=
确认不影响部署即可

2022-06-07 06:24 UTC, irwinsun requested changes
需要按上述整改

2022-06-07 09:53 UTC, sawyersong2 commented on src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/CredentialUtils.kt
> +    fun getCredential(
已删除

2022-06-07 09:55 UTC, sawyersong2 commented on src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/BuildType.kt
> +    THIRD_PARTY_BCS("蓝鲸容器平台", listOf(OS.LINUX), false, false, false),
THIRD_PARTY_BCS 已删除，PUBLIC_BCS作为BCS的构建类型，后续会在codecc插件 构建推送插件中用这个值识别具体在哪个构建集群，实现方式会不一样

2022-06-07 10:02 UTC, sawyersong2 commented on src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/enums/JobQuotaVmType.kt
> +    DOCKER_BCS("Docker on Bcs"),
对bcs资源单独做限额会使用

2022-06-08 06:06 UTC, irwinsun approved these changes

2022-06-08 06:06 UTC, merged