pref:插件自定义错误码管理 #7539
Tencent/bk-ci pull request #7825
Opened 2022-10-19 08:15 UTC by yjieliang

2022-10-24 04:14 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +                        if (it.length != 6 && (!it.startsWith("8"))) {
6和8最好不要写死了

2022-10-24 04:14 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +        strList.forEach { if (set.contains(it)) duplicateData.add(it) }
这是判断是否有重复的值吗？如果是判断是否重复，不应该是!set.contains(it)

2022-10-24 04:14 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +    override fun syncAtomErrorCodeConfig(
方法的关键步骤加点注释

2022-10-24 04:14 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> +        // 插件管理员才可修改
插件管理员才能修改这个是产品这么要求的吗

2022-10-24 04:14 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> +        val updateAtomFileContentresult = updateAtomFileContent(
updateAtomFileContentresult字段命名有问题

2022-10-24 06:43 UTC, yjieliang commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +        strList.forEach { if (set.contains(it)) duplicateData.add(it) }
这个是为了获取重复的errorCode，放在报错信息里
throw ErrorCodeException(
                            errorCode = USER_REPOSITORY_ERROR_JSON_ERROR_CODE_EXIST_DUPLICATE,
                            params = arrayOf(duplicateData.joinToString(","))
                        )

2022-10-24 08:14 UTC, irwinsun requested changes
CREATE TABLE IF NOT EXISTS

2022-10-24 08:14 UTC, irwinsun commented on support-files/sql/1001_ci_store_ddl_mysql.sql
> +CREATE TABLE `T_STORE_ERROR_CODE_INFO` (
CREATE TABLE IF NOT EXISTS

2022-10-24 08:27 UTC, yjieliang commented on src/backend/ci/core/artifactory/api-artifactory-store/src/main/kotlin/com/tencent/devops/artifactory/api/ServiceArchiveAtomResource.kt
> +        fileName: String,
已调整

2022-10-24 08:27 UTC, yjieliang commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +                        if (it.length != 6 && (!it.startsWith("8"))) {
已调整

2022-10-24 08:28 UTC, yjieliang commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> +        // 插件管理员才可修改
已调整

2022-10-24 08:28 UTC, yjieliang commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +    override fun syncAtomErrorCodeConfig(
已添加

2022-10-24 08:28 UTC, yjieliang commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
> +        val updateAtomFileContentresult = updateAtomFileContent(
已调整

2022-10-24 08:28 UTC, yjieliang commented on support-files/sql/1001_ci_store_ddl_mysql.sql
> +CREATE TABLE `T_STORE_ERROR_CODE_INFO` (
已调整

2022-10-24 09:01 UTC, irwinsun approved these changes

2022-10-26 03:31 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +        strList.forEach { if (set.contains(it)) duplicateData.add(it) }
val set = strList.toSet()
        val duplicateData = mutableListOf<String>()
        strList.forEach { if (set.contains(it)) duplicateData.add(it) } 这段逻辑没有看懂，这个不是计算重复的错误码的逻辑

2022-10-27 03:12 UTC, carlyin0801 approved these changes
ok

2022-10-27 06:37 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +    private var defaulAtomErrorCodoLength: Int = 6
单词拼错了，应该是ErrorCode和default

2022-10-27 06:37 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/AtomReleaseServiceImpl.kt
> +    private var defaulAtomErrorCodoPrefix: String = ""
同上，且没有默认值

2022-10-27 08:14 UTC, mingshewhe approved these changes

2022-10-27 08:15 UTC, merged