bug: 质量红线规则的生效流水线点进去为空 #7864
Tencent/bk-ci pull request #7865
Opened 2022-10-27 02:54 UTC by zhon-yu

2022-10-27 02:54 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-ci?pullRequest=7865) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-ci?pullRequest=7865) before we can accept your contribution.<br/><hr/>**v_ayzyzhong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-ci?pullRequest=7865) it.</sub>

2022-11-10 06:29 UTC, irwinsun requested changes
本次修改方式不合理，原来接口已经接入pipelineId列表，应该以该参数去查询，而不是全量从数据库中获取从内存中做过滤

2022-11-10 09:08 UTC, irwinsun commented on src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
> +            pipelineIds = pipelineIdList)
这里要传resultPipelineIds

2022-11-10 09:48 UTC, irwinsun approved these changes

2022-11-10 10:09 UTC, merged