feat: 新增获取模板接口，通过versionName入参来获取模板 #6416
Tencent/bk-ci pull request #7927
Opened 2022-11-04 03:25 UTC by yjieliang

[feat: 新增获取模板接口，通过versionName入参来获取模板](https://github.com/Tencent/bk-ci/commit/fcb588427c8f8baf0fb54327da20458848a5cb96) https://github.com/Tencent/bk-ci/issues/6416

2022-11-09 08:35 UTC, mingshewhe approved these changes

2022-11-10 06:33 UTC, carlyin0801 commented on src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwTemplateResourceV3.kt
> +    @ApiOperation("获取流水线模板详情", tags = ["v3_user_template_get", "v3_app_template_get"])
现在推进用V4的接口了，放到V4里面了吧

2022-11-10 06:33 UTC, carlyin0801 commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
> +                conditions.add(VERSION_NAME.eq(versionName))
一个versionName可能对应多条记录，你这个sql没有取最新的记录，而且根据versionName查询也没有走索引

2022-11-10 07:51 UTC, irwinsun requested changes
新接口都在最新版本中实现，V3不再新增接口

2022-11-10 08:27 UTC, yjieliang commented on src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwTemplateResourceV3.kt
> +    @ApiOperation("获取流水线模板详情", tags = ["v3_user_template_get", "v3_app_template_get"])
已调整

2022-11-10 08:27 UTC, yjieliang commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
> +                conditions.add(VERSION_NAME.eq(versionName))
已调整

2022-11-11 07:10 UTC, carlyin0801 approved these changes
ok

2022-11-16 04:06 UTC, irwinsun approved these changes

2022-11-16 04:07 UTC, merged